### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by peva3** [danopia/plex-backhaul#1]
Love the idea from the description, any more info on how you're going to go about designing this?

**Comment by danopia** [comment]
Hey, thanks for expressing early interest in this project :) I'll do a little bit of a braindump here since I haven't written any prose yet.

The basic idea of what I'm working on here is implementing a transparent proxy between Plex Web players and PMS instances which accelerates video streams. I noticed particularly bad performance streaming from the US to Europe during quarantine, to the point where even 320p transcodes would buffer, which suuucks.

I have yet to reach out to the Plex community to see if other people see similar problems with long distance streaming. I think it's fair to say that I'm currently in an experimental phase of trying different ideas and seeing what helps. I watch some TV every day so it's a pretty decent test cycle. Also, I'm not sure why but the Android app seems to stream ok on a connection where Plex Web buffers a ton.

So I guess my main question to you is if you've used Plex long distance, had trouble with buffering, which players had the trouble (web? android? both?), etc

## technical strategies

1. Performing parallel transfers using HTTP Range requests. This works like a traditional download accelerator, and PMS supports Range so it can be tested pretty easily. My trial implementation is pretty inefficient though, it lacks streaming. The impl is in `proxy/`
2. Performing parallel transfers using Websockets. This strategy is similar to the first, but involves a second program `backend/` running next to PMS on the server for the local server `endpoint/` to connect to. Thus I was able to implement it much more efficiently, meaning it can work on Direct Stream requests. This lets me Direct Play 10Mbps videos pretty nicely :)
3. Prefetching DASH segments. This should help with watching transcodes. It seems Plex Web is only downloading 1 second of video at a time (which is insane, I don't know when that started, 5s would be more reasonable). So if it takes 0.4sec to start requesting a file from the PMS on the other side of the world, you only have 0.6sec left to actually complete the transfer. I'm still experimenting on prefetch but it's pretty promising for transcodes and should work with either of the previously mentioned strategies.

One pain point I'm still working out is how to deal with required encryption. I require encrypted traffic on my PMS which makes it quite painful to set up proxies like this. I'll have to resolve this before I made a formal blog post showing off the software.

## Some graphics

Stock setup, no crazy crap like this repo:
<img width="676" alt="Screenshot 2020-06-03 at 17 05 57" src="https://user-images.githubusercontent.com/40628/83653799-83175300-a5bc-11ea-99af-18cfc1939dcb.png">

Adding a local accelerator (say, localhost:32400) which can perform Range requests and prefetch DASH segments:
<img width="677" alt="Screenshot 2020-06-03 at 17 14 26" src="https://user-images.githubusercontent.com/40628/83654671-b60e1680-a5bd-11ea-9c8d-c25cda723654.png">

Also adding an accelerator on the server side, using the websocket strategy:
<img width="677" alt="Screenshot 2020-06-03 at 17 10 38" src="https://user-images.githubusercontent.com/40628/83654351-44ce6380-a5bd-11ea-9881-7cc6f175253b.png">

I think the middle setup is easiest to setup, so I'm kinda aiming towards that 

## serviceworker?
Based on how Plex Web seems most impacted for me, I'm starting to wonder if it would make sense to instead write a ServiceWorker to install in the player's browser to handle the parallel transfers and prefetching. I'm not actually looking into this yet but it might be where stuff goes if installation/encryption proves tricky otherwise.

**Comment by peva3** [comment]
That's really awesome! Thanks for the in depth write up. I think a good place to look for inspiration would be the remote/distributed plex transcoders:

https://github.com/UnicornTranscoder/UnicornTranscoder
https://github.com/jeff-winn/PlexTranscoder

They're done a lot of cool work about splitting up video transcodes and they might even have a good example of a proxy you could look at.

**Comment by danopia** [comment]
I've heard of those alternate encoder setups. I think we're solving different problems, in fact you could probably combine the two projects in one setup.

I don't have many users and my PMS box is a pretty decent i5 so the transcode side is not the bottleneck at all. I'm focusing on getting the transcoded bytes transferred fast enough instead of having the transcoding ready sooner. It seems like Unicorn does do some proxying though, so maybe there would be some lessons there on encryption.

Thanks for the links

**Comment by peva3** [comment]
No problem. I'd also love to be a guinea pig for whatever you come up with, let me know, I have a lot of EU users.

**Comment by danopia** [comment]
Hey, I ended up dropping this project because the Internet between my Plex and my important streaming devices cleared up and the bandwidth issues went away. So I'll archive the repo shortly. I hope all's well over there :)
